### ISSUE TITLE
 No file 'LUT.npy' called

### ISSUE THREAD

**Issue by Pasanlaksitha** [NajmAjmal/video-to-ascii#1]
C:\Users\\video-to-ascii>python main.py video.mp4
Traceback (most recent call last):
  File "C:\Users\video-to-ascii\main.py", line 17, in <module>
    LUT = np.load("LUT.npy")
          ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Python312\Lib\site-packages\numpy\lib\npyio.py", line 427, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'LUT.npy'

opencv installed with numpy 
program run without virtual env

**Comment by maxfarrell** [comment]
Same here
